version: '3.6'

services:
    mysql:
        restart: always
        image: mysql:8.0
        container_name: prowess_db
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - '3306:3306'
        expose:
          - 3306
        environment:
          - MYSQL_DATABASE=prowess_db
          - MYSQL_ROOT_USER=root
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_ROOT_HOST=%
          - MYSQL_USER=prowess
          - MYSQL_PASSWORD=P@ssw0rd
        volumes:
          - db:/var/lib/mysql
          # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
          - my-network
    backend:
        restart: always
        image: prowess/backend
        container_name: prowess_backend
        ports:
          - 3000:3000
        build:
            context: ./prowess-backend
            dockerfile: ./Dockerfile
        env_file:
          - ./prowess-backend/.env
        volumes:
            - ./prowess-backend:/backend
            - ./scripts:/scripts
            - '/backend/node_modules'
        links:
            - mysql
        depends_on:
          - mysql
        networks:
          - my-network

        command: >
            sh -c "/scripts/wait-for-it.sh mysql:3306 -- npm run start:dev"
    frontend:
        restart: always
        # image: prowess/frontend
        container_name: prowess_frontend
        build: ./prowess-frontend/
        ports:
          - "4200:80"
        # # links:
        # #   - backend


networks:
  my-network:
    driver: bridge
    
volumes:
  db:
    driver: local
